Add SSH HS to customize script.

diff --git a/customize b/customize
--- a/customize
+++ b/customize
@@ -105,4 +105,79 @@ chmod +x ${ROOTDIR}/remove_ssh_host_keys.sh
 chroot ${ROOTDIR} /remove_ssh_host_keys.sh
 rm ${ROOTDIR}/remove_ssh_host_keys.sh
 
+
+cat <<'EOF' > ${ROOTDIR}/configure_ssh_copy_client_key.sh
+#!/bin/bash
+su -c 'mkdir /home/lepidopter/.ssh' lepidopter
+# FIXME: change ssh public key
+echo sshpublickeyhere > /home/lepidopter/.ssh/authorized_keys
+sed -i 's|[#]*PasswordAuthentication yes|PasswordAuthentication no|g' /etc/ssh/sshd_config
+sed -i 's|[#]*PermitRootLogin yes|PermitRootLogin no|g' /etc/ssh/sshd_config
+sed -i 's|[#]*ListenAddress 0.0.0.0|ListenAddress 127.0.0.1|g' /etc/ssh/sshd_config
+history -c
+EOF
+
+chmod +x ${ROOTDIR}/configure_ssh_copy_client_key.sh
+chroot ${ROOTDIR} /configure_ssh_copy_client_key.sh
+rm ${ROOTDIR}/configure_ssh_copy_client_key.sh
+
+
+cat <<'EOF' > ${ROOTDIR}/etc/init.d/generate_ssh_hs
+#!/bin/sh
+### BEGIN INIT INFO
+# Provides:          generate_ssh_hs
+# Required-Start:    $local_fs $remote_fs $network
+# Required-Stop:     $local_fs $remote_fs $network
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Generate SSH Hidden Service (HS)
+# Description: This script will generate the SSH HS keys and onion address.
+### END INIT INFO
+
+# TODO: send ssh hs onion address to a web hidden service,
+# something like:
+# onionaddress=`cat /home/lepidopter/hs/hostname`
+# usewithtor curl http://webserveronionaddress/$onionaddress
+# In case tor fail to start, the ssh hs will fail too,
+# and the onion address won't be send to the web hidden service
+
+. /lib/lsb/init-functions
+
+set -e
+
+case "$1"
+  in  start)
+    log_daemon_msg "Creating ssh HS address..."
+    nohup sh -c "if [ ! -d /home/lepidopter/hs ]; then mkdir -p /home/lepidopter/hs; fi && \
+      chown debian-tor /home/lepidopter/hs && \
+      printf 'HiddenServiceDir /home/lepidopter/hs\nHiddenServicePort 22 127.0.0.1:22' >> /etc/tor/torrc && \
+      update-rc.d tor enable && sync && \
+      update-rc.d generate_ssh_hs remove && \
+      printf '\nfinished\n' && invoke-rc.d tor start" > /var/log/generate_ssh_hs.log 2>&1 &
+    log_end_msg $?
+    ;;
+  *)
+    log_success_msg "Usage: $0 start "
+    exit 3
+    ;;
+esac
+exit 0
+EOF
+
+cat <<'EOF' > ${ROOTDIR}/configure_ssh_hs.sh
+#!/bin/bash
+echo 'deb http://ftp.de.debian.org/debian wheezy-backports main' > /etc/apt/sources.list.d/backports.list
+apt-get update -qq
+apt-get install -y tlsdate
+apt-get install -y tor
+update-rc.d tor disable
+chmod 755 /etc/init.d/generate_ssh_hs
+update-rc.d generate_ssh_hs defaults
+history -c
+EOF
+
+chmod +x ${ROOTDIR}/configure_ssh_hs.sh
+chroot ${ROOTDIR} /configure_ssh_hs.sh
+rm ${ROOTDIR}/configure_ssh_hs.sh
+
 echo "Customize script finished successfully."
