Update after updating ChaneLog, add git tag, format
The release should be tagged after the changes of ChangeLog though it's
better if the user initiate the git tag manually.
* User inputs git tag parameters that will be used to generate git tag
  command, update ChangeLog version and update lepidopter_version
* Minor format fixes

Thanks @hellais for comments

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -4,16 +4,54 @@ set -e
 
 VERSION_FILE="lepidopter-fh/etc/lepidopter_version"
 
-# First issue a release
-# git tag -a vX.X.X -m "Release msg" -s -u <keyid>"
+usage() {
+    echo "usage: $0 [options]"
+    echo -e "\t-a git tag annotation (X.X.X)"
+    echo -e "\t-m git tag message (\"msg\")"
+    echo -e "\t-u git tag GPG keyid (0xXXX)"
+}
 
-echo "Using tag reference: $(git tag -n |tail -n1) as release tag."
+if [ $# -ne 6 ] ; then
+    usage
+    exit 1
+fi
 
-NEW_RELEASE_VER=$(git describe --abbrev=0)
+while getopts "a:m:u:" opt; do
+    case $opt in
+      a)
+        annotation=${OPTARG}
+        ;;
+      m)
+        message=${OPTARG}
+        ;;
+      u)
+        keyid=${OPTARG}
+        ;;
+      h)
+        usage
+        exit 0
+        ;;
+     \?)
+        echo "Invalid option: -$OPTARG" >&2
+        usage
+        exit 1
+        ;;
+      :)
+        echo "Option -$OPTARG requires an argument." >&2
+        usage
+        exit 1
+    esac
+done
 
-echo ${NEW_RELEASE_VER} > ${VERSION_FILE}
+echo "Using tag reference: ${annotation} as release tag.\n"
+
+echo ${annotation} > ${VERSION_FILE}
 
 mv ChangeLog.md ChangeLog.md.old
-echo "#Lepidopter ${NEW_RELEASE_VER} [`date +%Y-%m-%d`]" > ChangeLog.md
+echo "# Lepidopter v${annotation} [`date +%Y-%m-%d`]\n" > ChangeLog.md
 cat ChangeLog.md.old >> ChangeLog.md
 rm ChangeLog.md.old
+
+# git tag -a X.X.X -m "Release msg" -s -u <keyid>"
+echo "If you are happy with ChangeLog content, commit changes.\n"
+echo "When ready use: git tag -a ${annotation} -m "${message}" -s -u ${keyid}"
